### ISSUE TITLE
War Thunder 2.0 Bugreports

### ISSUE THREAD

**Issue by RadonSound** [GaijinEntertainment/fmod_studio_warthunder_for_modders#44] opened 2020-11-17 21:22 UTC
Hello!
I would like to start this post for bugreports for the new Update "New Power".
anyway i found 3 bugs so far (more or less some majorbugs)

1. Tank AI engines are muted (only tracks can be heard)
2. The FlaRakRad has no engine sound (only wheels can be heard)
3. The Harrier has no engine sound

Watch here  https://www.youtube.com/watch?v=bazJ3cvjIdc&feature=youtu.be 
please check the chapters in the video

These are the only things i found so far

**Comment by RadonSound** [comment] 2020-11-19 02:13
the impact sound for tanks when getting killed is muted

**Comment by Uchuujin01** [comment] 2020-11-19 11:19
Hello!
1. - please look at this topic https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/issues/45
2. - yes, it has a new engine sound events now.
3. - same for the Harrier.

"the impact sound for tanks when getting killed is muted" - this is a known issue, we working on it now, it is not depends on fmod project.

**Comment by RadonSound** [comment] 2020-11-19 16:21
Thanks for the info.

With the comment from the post #45  " "i would rather have the current version fixed than a new project." - I'm not sure I understand you. What's the difference between fixing the current version and a prepearing a new one? "

i meant if the current project still can be used in future besides a new one ( so there is one new and one old project but both works ) . So is it possible to add the new sound events manually?

**Comment by RadonSound** [comment] 2020-11-19 19:39
Also for the engine sounds, did i make this corretly (marked red)? do i have to remove some parameters so its only the rpm,load,loadswitch and broken parameters left on the top (marked orange) ? and is it normal that the tracks have the #unassigned tag (marked blue) ? And should i leave the distance module as it is (yellow) ? and/or do i have to change something in the tracks (green) ?


![Screenshot (431)](https://user-images.githubusercontent.com/67481432/99714642-1d554f80-2aa6-11eb-87d1-27da7ba39151.png)

im trying make this work like you said in the post #45 🙁

**Comment by RadonSound** [comment] 2020-11-19 20:56
Ok so i found out when i rightclick on the engine file then [ Assign to Bank > tanks > tanks_engines ✔] the #unassigned tag is gone and the ai engines can be heard in game but now i have to simplify them because in the first try it kinda sound like the game doesnt know wich engine sound it should play when i stand close to some other tank groups , but i think this can be fixed by simplify the events as you said 
only figure out how

**Comment by Uchuujin01** [comment] 2020-11-19 23:27
"i meant if the current project still can be used in future besides a new one ( so there is one new and one old project but both works ) . So is it possible to add the new sound events manually?"
Of course. For example, you can copy some new sound events from the new version of a project (when it will be released), to your mod project.

**Comment by Uchuujin01** [comment] 2020-11-19 23:35
"Also for the engine sounds, did i make this corretly (marked red)?" - yes.

"do i have to remove some parameters so its only the rpm,load,loadswitch and broken " - Yes, but you can leave EventConeAngle, if you want your events to change depend on listener angle.

"nd is it normal that the tracks have the #unassigned tag (marked blue) ?" - No, you should add it to tanks_engines sound bank.

"And should i leave the distance module as it is (yellow)" - You can add a distance attenuator module to master track of engine sound event.

"and/or do i have to change something in the tracks (green) ?" - yes, reduce the number of tracks. Now it is quite heavy sound event, leave just tracks "load", "loadswitch", and "broken" tracks.

**Comment by RadonSound** [comment] 2020-11-20 01:27
So i did this for example and its working quite well . layer04 is loadswitch , layer06 is load and the 3th it broken . Is this the Distance module (on the bottom) you've mentioned?

![Screenshot (434)](https://user-images.githubusercontent.com/67481432/99742847-ad11f280-2ad4-11eb-9a38-e5ae98acae2c.png)

I noticed that some layers/tracks have Fader > [Automation & Modulation] like: Distance , load , broken .  Is the Distance one important? since the Distance is controlled in Master.
![Screenshot (435)](https://user-images.githubusercontent.com/67481432/99744069-42ae8180-2ad7-11eb-9d18-bfd22609317a.png)
(example of layer06)

offtopic: im sorry if sometimes im asking too much for things . i just want to be sure and dont cause any problem ingame although im really thankful for all the help and giving us the possibility to create soundmods  ✌

**Comment by Uchuujin01** [comment] 2020-11-20 13:40
"Is this the Distance module (on the bottom) you've mentioned?" - yes, it is. But I think it needs some adjustment.

"I noticed that some layers/tracks have Fader > [Automation & Modulation] like: Distance , load , broken . Is the Distance one important? since the Distance is controlled in Master." - - yes, you can delete it, it is no longer needed.

"offtopic: im sorry if sometimes im asking too much for things . i just want to be sure and dont cause any problem ingame although im really thankful for all the help and giving us the possibility to create soundmods ✌" - I'm glad to help ) Feel free to ask about the project adjustments, it's not hard for me to answer at all ) And thank you for your work!

**Comment by RadonSound** [comment] 2020-11-22 10:57
Since 2 day i kinda noticed that the ai shot sounds have a big delay from the actual shot. Ive cecked already if the speed of sound option ingame is turned on but it isnt. is there a way to change/fix that?

**Comment by Uchuujin01** [comment] 2020-11-25 18:23
"Since 2 day i kinda noticed that the ai shot sounds have a big delay from the actual shot. Ive cecked already if the speed of sound option ingame is turned on but it isnt. is there a way to change/fix that?"
Hello! I'm afraid I can't see any problem in shots, they work as intended, sound appears immedeately. And I have no such reports from players. Maybe you can make a video, and describe conditions of this effect?

**Comment by RadonSound** [comment] 2020-11-26 10:16
https://www.youtube.com/watch?v=XwE4ugJQcDM&feature=youtu.be

So i tried my best to record it (wasnt really easy) and add a slowmotion part. 
There is estimated a sound delay about 0.7-1 Second over a 300 Meter distance. 

On the first Clip i took almost a second for the sound (M48 - ~700m Distance) 

On the last part where the listener was right next to the ZSU, the sound where played immedeatly. But where the listener is on the ZTZ59 Tank (00:22) , the delay was around ~0.6  Seconds and that was around 200m distance. 

It's really strange because since the update, i didnt changed anything in the AI shot modules (i only use Shot and Tail in one 
AI shot event) 
i only worked on AI Engine sounds so far

**Comment by RadonSound** [comment] 2020-11-28 09:29
I suspect it is the Tail track but all of them only have a distance module for the loudness

**Comment by Uchuujin01** [comment] 2020-11-30 17:04
Hello! I can't say anything about shot sound delay, still didn't check it, I'll try tomorrow, and write to you then.

**Comment by RadonSound** [comment] 2020-11-30 23:38
hello,
So i started to recover the older project version like you said to simply copy the new events to the older project. It works pretty well so far . now i can hear the Harrier and the FlaRakRad , i even copyd the whole ai engine file to the older project wich was alot easier than adjust every single engine.
(yes i Assign them all to the correct Banks with rightclick) 

The only thing that doenst want to work properly are the new music events. Because i dont know if its any possible to copy the new "aircraft_music_2.bank + aircraft_music_3.bank" wich contains the new menu/login music and the toptier music events to the older project , i created them in my project i tried to make them as similar as possible to the new project.
Ingame the "new_menu" (login theme) plays, but it cant be controlled by the [Music Volume in Menu] ingame but only with the Main [Volume] setting.

I actually tried to start with the new updated project, but the way how events like the "100mm_d10t_interior" are now played, doesnt really matchup anymore with the sounds i use. It feels like it has a stronger "Surroundsound" effect , than the older project i use. 
I know this supposed to be more realistic like in a real tank turret, but as i sayd, it doesnt match anymore with the sounds i use like instead of playing in stereo, it sounds like its playing in front of me with a bit more bass . 
I presume this effect is controlled by the Masterbank so i dont think i can change somthing there .

**Comment by RadonSound** [comment] 2020-12-03 03:43
*just out of curiosity, in the past i sometimes made some mistakes in fmod like had some wrong adjustments in the master track or missed to adjust some distance modules (leaded to hearing AI sounds literally from enemy spawn). because i always go into a custom battle with bots to test, i was able to fix those issues pretty fast. but always had this one question in mind, can you actually run into serious ingame problems by playing with incorrect settings in fmod? i mainly asking this because im always a bit afraid by change some larger settings in fmod or in my situation now, i copy&pasted some events from the newer project into the older one for instance the 120mm_jspg (if i remember it right) and the new engine events. And all of these events have a different master track compared to the other ones in the older project. and i have a little uncomfortable feeling about it, if there could anything happen when those newer master tracks from the events meet up with the older project. could this lead somehow into a problem? 
I suffer a bit from "anxiety disorder" wich is why i always have respect (ok im actually scared) when i comes about dealing with some more serious things like master tracks , etc.. 
i hope you understand) i do not want to risk anything

**Comment by Uchuujin01** [comment] 2020-12-03 09:14
Hello! About new action music, please, be sure it is in "music" group in mixer view, and new music intro is in "music menu" group.
The same concerning AI engines, be sure they in proper place in Mixer view.
About inrerior reverberation, please, check Mixer view in the new project. It contains a lot of new Return buses now. They contains convolution reverb modules. And, dont forget about corresponding snapshots (field, city_far, city_close, sea, air, cockpit, tank).

**Comment by Uchuujin01** [comment] 2020-12-03 09:15
Sorry for the answer delay, btw.

**Comment by Uchuujin01** [comment] 2020-12-03 09:23
I'm not sure I understood you correclty, but, I think, you should pay attention to what happent with your events in Mixer window, when it comes to copy-paste actions. I think, the most frequent problems come from misunderstanding the main concepts of Fmod - groups -> VCA -> Snapshots. Try to copy the new sound event from new project to your project, and then see what's changed in your Mixer window.
I hope I understood your problem right (the lack of knowledge in English, sorry, working on it), but, feel free to write your questions, I'll try to help.

**Comment by RadonSound** [comment] 2020-12-03 13:43
![Screenshot (461)](https://user-images.githubusercontent.com/67481432/101022947-5c89a300-3572-11eb-8321-1788cff2968f.png)
I think i see what you mean,
The few events in the green box are the one i keeped from the old project to see if there is any difference. The other events in the red box are the copy-pasted events. So all i have to do is drag'ndrop the new events in mixer into the ground group? And the same for the music (in music group)? Also in the Mixing desk the (for instance) 100mm_d10t_interior (from old project) and the 105mm_kwk46_interior (copyd from the new project) have pretty much the same settings with all the regulators same with the modules on the bottom (like Fader - All_Mix_Attenuation_Gain - etc ) so i dont have to change something here?

**Comment by RadonSound** [comment] 2020-12-03 13:51
Also dont feel sorry about knowledge in english, thus far it is really good. even i have problems mainly when it comes about punctuation ( . , ! ? ) wich is why sometimes my block of text is a bit hard to understand

**Comment by Uchuujin01** [comment] 2020-12-03 16:16
Exactly, just place your copied sound events in the corresponding groups (where your old sound events placed), so the VCA will be able affect them.
"Also dont feel sorry about knowledge in english, thus far it is really good" - you are too kind, thank you ) Sometimes it is not enough to understand some complicated situations, but I'm learning )

**Comment by RadonSound** [comment] 2020-12-03 18:43
So everything now got his right place in mixer. AI engine volume is now separately from own engine 👍
Is it necessarily to create new banks for new music? like aircraft_music_2 & 3 
or can i just assign the copyd events (menu_new etc.) to the defaul aircraft_music.bank ? (yes i droped them in mixer in the correct group)

**Closed** 2020-12-14 03:56 UTC
