### ISSUE TITLE
Are MGs and SPAA broken now?

### ISSUE THREAD

**Issue by 787992** [GaijinEntertainment/fmod_studio_warthunder_for_modders#56] opened 2020-12-18 09:38 UTC
Hello, my project file used loops for mgs and spaa guns, now it's broken, any idea how to fix it?

Edit: looks like it's oneshot events now and uhh i don't really wanna re-do anything once again

**Comment by Uchuujin01** [comment] 2020-12-18 09:41
Hello! I'll release the updated project in the beginning of the next week. mgs abd spaa not works in one-shot way, you can replace all scatterers with their contained shot event with parameter trigger on_shot, just like in big caliber cannons.

**Comment by Uchuujin01** [comment] 2020-12-18 09:44
It was necessary update, because newest version of fmod, 2.1.6, has broken scatterer instruments, thes doesn't work in normal way. So we urgently needed to rework mgs and spaa principles of work.

**Comment by Uchuujin01** [comment] 2020-12-18 09:45
And we needed to move on fmod 2.1.6 because of many PS5 fixes. It is important for game engine perfomance.

**Comment by 787992** [comment] 2020-12-18 09:47
> It was necessary update, because newest version of fmod, 2.1.6, has broken scatterer instruments, thes doesn't work in normal way. So we urgently needed to rework mgs and spaa principles of work.

Yeah, understandable. Is it possible to make some kind of switch to move from oneshot and vice versa? So mods can stay alive a little bit longer :)

**Comment by 787992** [comment] 2020-12-18 09:58
Honestly i spent numerous hours making loop lines for all mgs and spaas, now it's all gone :(

**Comment by Uchuujin01** [comment] 2020-12-18 10:02
We will discuss it, I totally understand this issue. It was quite unpredictable situation with fmod scatterers, so we needed to act fast, to avoid sound problems with new update.

**Comment by 787992** [comment] 2020-12-18 10:17
> We will discuss it, I totally understand this issue. It was quite unpredictable situation with fmod scatterers, so we needed to act fast, to avoid sound problems with new update.

Thank you very much, hope it turns out in positive way.

**Comment by RadonSound** [comment] 2020-12-18 10:18
@787992 wich project do you use? 
The only loop events i have are for planes but MG's and SPAA's still working for me. 

https://i.imgur.com/XYX8QZC.png does this mean these events are not supported anymore? im afraid i dont understand the situation

**Comment by 787992** [comment] 2020-12-18 10:24
> @787992 wich project do you use?
The only loop events i have are for planes but MG's and SPAA's still working for me.

https://i.imgur.com/XYX8QZC.png does this mean these events are not supported anymore? im afraid i dont understand the situation

That means, events will be triggered according to gun rpm - each shot and not inside loop line.

**Comment by Uchuujin01** [comment] 2020-12-18 10:26
@RadonSound as I said above, the mgs and spaa now works in one-shot way, so all you need to do - is take your sound event that placed in scatterer, and place it instead of scatterer. Like big cannons, it should have trigger parameter on_shot.

**Comment by Uchuujin01** [comment] 2020-12-18 10:28
@RadonSound I'm very sory for the inconveniencs, it was very urgent and necessary change, because in fmod 2.1.6 our weapon became sound unstable and awkward.

**Comment by RadonSound** [comment] 2020-12-18 10:59
> @RadonSound as I said above, the mgs and spaa now works in one-shot way, so all you need to do - is take your sound event that placed in scatterer, and place it instead of scatterer. Like big cannons, it should have trigger parameter on_shot.

I understand so is has to be in this way now?
![Screenshot (500)](https://user-images.githubusercontent.com/67481432/102605752-0eee6800-4126-11eb-83d1-a2fee4207409.png)

> @RadonSound I'm very sory for the inconvenience, it was very urgent and necessary change, because in fmod 2.1.6 our weapon became sound unstable and awkward.

May i ask wich version the 2.1.6 is? is it something different than 2.00.09? i never really paid attention since it became 2.00.09

**Comment by Uchuujin01** [comment] 2020-12-18 11:17
@RadonSound yes, exactly. Regarding to version, 2.1.6 don't different strongly from 2.0.9. Banks from 2.0.9 version work with 2.1.6 game fmod library. But it is recommended to update your project (open and save in 2.1.6).

**Comment by 787992** [comment] 2020-12-18 11:33
My hopes on thingy that reverts oneshots to loops, (since mod support exists only for PCs)
Personally i like loops more, it also more reliable in terms of optimization.

**Comment by Uchuujin01** [comment] 2020-12-18 11:38
@787992 I'm afraid we can't revert to loops, since current one-shot model is more realistic, and since fmod scatterers no longer works. Firelight answered that they will fix scatterers, but it is too much work to revert all over again ( But, we'll discuss, could we make a sound mod option for weapon loops.

**Comment by Uchuujin01** [comment] 2020-12-18 11:39
@787992 I'll let you know about it in the beginning of the next week.

**Comment by Uchuujin01** [comment] 2020-12-18 11:44
@787992 regarding to optimisation, it is not so simple. Loops more convenient for CPU, yes, but it is too big for storage in memory. It depends of compression mode, of course, but you should remember - the more compression - the more CPU usage. I'm really don't like loops, because they sounds more flat and repeatabe than one-shot sequences. And, you can't make a single shot with looped weapon, it's allways will be several shots.

**Comment by 787992** [comment] 2020-12-18 12:11
> @787992 I'm afraid we can't revert to loops, since current one-shot model is more realistic, and since fmod scatterers no longer works. Firelight answered that they will fix scatterers, but it is too much work to revert all over again ( But, we'll discuss, could we make a sound mod option for weapon loops.

Yeah, i meant option and not revert everything back, thanks for answers though, will wait for further solutions.

> @787992 regarding to optimisation, it is not so simple. Loops more convenient for CPU, yes, but it is too big for storage in memory. It depends of compression mode, of course, but you should remember - the more compression - the more CPU usage. I'm really don't like loops, because they sounds more flat and repeatabe than one-shot sequences. And, you can't make a single shot with looped weapon, it's allways will be several shots.

I believe 2.0 update brought multi-thread support, so CPU usage shouldn't be a problem here, sadly there can't be separation between consoles and PCs versions, since only consoles slowing down progress.
One shot system is great though, but few things that actually stops using it: Non-consistent rpm - the gun will not sound automatic, rather fast firing rifle, fmod simply refuses to play constant rpm above 600 (you can already notice it in game with vanilla)
Less creativity to make individual gun "voices": some guns cam make unique effects only with loop lines

Regarding loop lines being flat and repeatabe this is also debatable, any guns irl start shooting with same rpm and tonality but after couple of shots rpm slightly shifts thus making "differences". (check out how COD MW 2019 did it's sound design)
You can also imitate that by making base (body loop) and hifi (mech loop) so hifi had random shift or pitch and voila gun that shoots with constant rpm and has random differences, it will sound the same at start but won't be exactly the same after couple of rounds.

Oh and yea i think on_shot parameter (not perfect) solved problem with several shots with loop lines.

**Comment by Uchuujin01** [comment] 2020-12-18 12:21
@787992 I agree, you can do the shot sounds grean, with both loop and one-ahot methods. Both methods have their pros and cons. But imho one-shot system more flexible. I should notice though, after the new change we don't use scatterers for one shots, so it become more stable on powerful computers. But, now it depends on fps. So, we will adjust the system in future, we should make it adaptive to fps drops.

**Comment by 787992** [comment] 2020-12-18 12:42
> I agree, you can do the shot sounds great, with both loop and one-shot methods. Both methods have their pros and cons. But imho one-shot system more flexible.

True, you can make changes on fly, but in any case i just put my few cents here :)
Will look forward for answer regarding option for sound mods.

**Comment by Uchuujin01** [comment] 2020-12-18 15:29
@787992 @RadonSound we discussed the problem with one-shot and loop weapon playbach method. 99% probability that we'll add a flag variable in config.blk for loop-style/one-shot playpack support choose. We'll add this feature next week. I'll inform you about it.

**Comment by 787992** [comment] 2020-12-18 15:55
> we discussed the problem with one-shot and loop weapon playbach method. 99% probability that we'll add a flag variable in config.blk for loop-style/one-shot playpack support choose. We'll add this feature next week. I'll inform you about it.

Can't describe how I grateful for that, thank you very much Anton.

**Comment by RadonSound** [comment] 2020-12-18 22:05
Oh that sounds nice! i have plenty of loop sounds for Mg's and SPAA's that i would love to use. some i even teared down into single shots but the result was a bit disappointing.

**Comment by Uchuujin01** [comment] 2020-12-18 23:06
@RadonSound yes, you got it right. But, you could use loops before this update, instead of scatterer instruments. This feature just allows to use old (before this update) loop-style sound of mgs and spaa.

**Comment by RadonSound** [comment] 2020-12-18 23:52
Oh.
I always wanted to use for instance the old " mg_8mm_dt_loop " (wich is located in files here: Assets\tanks\weapon\machineguns\dt\ )
But i didnt know how to use it

**Comment by Uchuujin01** [comment] 2020-12-22 11:06
@787992 @RadonSound hello! We added this loop compatibility mode to tomorrow's patch. So, you have to inform your mod users that they have to add useLoopsForGunSound:b=yes in their config.blk. Also, we will add this notion in our sound mods wiki page.

**Comment by RadonSound** [comment] 2020-12-22 21:38
Thank you so much for doing this!
 but one question, how do i make a loop event for mg's and spaa's ? maybe a screenshot can help)

**Comment by Uchuujin01** [comment] 2020-12-23 07:45
@RadonSound you have to choose single instrument for your loop, then swinch on loop property for this instrument, and then add a trigger condition for on_shot parameter with value 1. That's all, when play cursor stops at sustain point upon theis container, and on_shot parameter set to 1, loop starts play.

**Comment by RadonSound** [comment] 2020-12-23 16:07
well i think i (not) made it as you said but for some reasons i doesnt want to work either the sound playes in loop but doesnt want to stop, or a new loop start every second ingame when hold firekey for MG's
![Screenshot (526)](https://user-images.githubusercontent.com/67481432/103014118-8402d880-453e-11eb-8d1e-bd5c0b3e3c1f.png)
![Screenshot (527)](https://user-images.githubusercontent.com/67481432/103014130-86653280-453e-11eb-9d5f-261d51edc0ae.png)

**Comment by 787992** [comment] 2020-12-23 16:27
> @787992 @RadonSound hello! We added this loop compatibility mode to tomorrow's patch. So, you have to inform your mod users that they have to add useLoopsForGunSound:b=yes in their config.blk. Also, we will add this notion in our sound mods wiki page.

Cool, but yeah as said above loop system is not working.

**Comment by Uchuujin01** [comment] 2020-12-25 09:55
@RadonSound loop system is work now. I see one mistake in your screenshot. Look, you set your loop to only once playing (digit near the loop icon on instrument). So it ends, and starts then. 

@787992 Are you sure? I checked it - works for me now. Describe your realisation, add screenshot please.

**Comment by 787992** [comment] 2020-12-25 11:29
> @787992 Are you sure? I checked it - works for me now. Describe your realisation, add screenshot please.

Just check it, still doesn't work. Didn't touch anything since oneshot implementation, so it worked before. Exact same feature with on_shot param.
Same behaviour in-game - sound doesn't stick on sustain point (or loop point) it starts from begining like oneshot

It feels like useLoopsForGunSound:b=yes not applies in config file, please check if such line exists in allowedconfigoverrides

**Comment by 787992** [comment] 2020-12-25 13:23
> @787992 Are you sure? I checked it - works for me now. Describe your realisation, add screenshot please.

Ok, checked it twice also with datamined files
![unknown](https://user-images.githubusercontent.com/63158562/103135985-729c0680-46cd-11eb-9732-32150f23d58e.png)
Such allowed line is not here.

**Comment by Uchuujin01** [comment] 2020-12-25 14:05
"Such allowed line is missing." - this is not the allowed line, it is default lines, most probably. It is no matter, anyway. Ok, I'll check asap on production client, haven't checked it yet, only on our dev client, it works fine there.

**Comment by 787992** [comment] 2020-12-25 14:06
> Ok, I'll check asap on production client, haven't checked it yet, only on our dev client.

Oh that's probably the reason :)

**Comment by Uchuujin01** [comment] 2020-12-25 14:18
I doubt so, because this commit is definitely was released in yesterday's update. But it needs to be checked definitely.

**Comment by 787992** [comment] 2020-12-25 14:32
Alrighty then, will wait for confirmation :)

**Comment by Uchuujin01** [comment] 2020-12-25 14:45
I must say, just checked it on production - everything works fine now on production. My config:
sound{
  speakerMode:t="stereo"
  fmod_sound_enable:b=yes
  enable_mod:b=yes
  useLoopsForGunSound:b=yes
}

Please, check your single instrument settings again, it should work, definitely. I'm 100% sure now, it now works on production client.

**Comment by Uchuujin01** [comment] 2020-12-25 14:47
You can drop screenshots of your event here, btw, I'll check it.

**Comment by RadonSound** [comment] 2020-12-25 14:59
I will check mine now.

**Comment by RadonSound** [comment] 2020-12-25 14:59
So the 1 near the loop icon has to be ∞?

**Comment by 787992** [comment] 2020-12-25 15:23
> You can drop screenshots of your event here, btw, I'll check it.

Weird, on my side, nothing have been changed, since oneshot system implementation.

![image](https://user-images.githubusercontent.com/63158562/103137787-3d97b000-46dd-11eb-94f1-d297cfebc609.png)

It should work exactly the same as before. Timer should stick on sustain point, everything triggering with on_shot param, by releasing it loop stops and plays tail or echo.

**Comment by Uchuujin01** [comment] 2020-12-25 15:27
@787992 @RadonSound did you move your projects on 2.1.6 versions, btw?

**Comment by Uchuujin01** [comment] 2020-12-25 15:28
I made an example video for you, just in case:

https://user-images.githubusercontent.com/26138230/103137995-00ccb880-46df-11eb-8459-760759728af8.mp4

**Comment by 787992** [comment] 2020-12-25 15:32
> did you move your projects on 2.1.6 versions, btw?

Damn, that's what i missed looks like (dumb me)

> I made an example video for you, just in case:

Yeah it works exactly the same.

**Comment by Uchuujin01** [comment] 2020-12-25 15:35
Banks, made in 2.0.9, works not fine with fmod v 2.1.6 libs. They work, but, sometimes with unexpected glitches.

**Comment by RadonSound** [comment] 2020-12-25 15:37
I was about to ask if its because the new version. 
can i update the project by simply install the fmod 2.1.6?

**Comment by Uchuujin01** [comment] 2020-12-25 15:39
@RadonSound yes, you have to open your project in 2.1.6 version. I thought I did mention that before.

**Comment by RadonSound** [comment] 2020-12-25 15:40
Oh yes. sorry i forgot

**Comment by RadonSound** [comment] 2020-12-25 16:27
https://user-images.githubusercontent.com/67481432/103138655-eee61800-46d4-11eb-984f-3ff0f92a43e8.mp4

I updated it and now its doing this. I tried to rearrange the event tracks or move the sustain point or change something here and there, it always doing this.

Well i think i gonna make the step and start with a new project (mine is still from July this year) there are just too many things missing due to added vehicles and sounds in the past

**Comment by RadonSound** [comment] 2020-12-25 16:31
I will come back here if something is still not working 👍 (maybe i did something wrong in the event) But it was just for sure that i need to update my project sooner or later

**Comment by Uchuujin01** [comment] 2020-12-25 16:37
@RadonSound yes, please, check your sound events, it should work now. Take a look mt my example video above, I hope it will be helpful.

**Comment by 787992** [comment] 2020-12-25 18:43
Okay, I quickly made setup for clean project and imported loop lines... And i'm out of ideas.



https://user-images.githubusercontent.com/63158562/103140550-ddaf0280-46f8-11eb-8fdf-0d75f184e605.mp4

Everything made exactly same like previous method
However game refuses to play it correctly

https://user-images.githubusercontent.com/63158562/103140601-9c6b2280-46f9-11eb-9071-7e6863283e07.mp4
Note, i didn't touch vanilla interior oneshots and it plays correctly ingame, so this is defenitely not an event issue, switch from oneshots to loop bugged or not working somehow on my side.

![image](https://user-images.githubusercontent.com/63158562/103140648-2ca96780-46fa-11eb-964b-30d59d271f89.png)

**Comment by Uchuujin01** [comment] 2020-12-25 19:18
@787992 vanilla interior shouldn't play correctly if you insert useLoopsForGunSound:b=yes. I seems useLoopsForGunSound:b=yes doesn't work for you, I don't know why. But, I tested production version today - it works correctly for me, with useLoopsForGunSound:b=yes. Send me your clog file, please.

**Comment by 787992** [comment] 2020-12-25 19:50
> vanilla interior shouldn't play correctly if you insert useLoopsForGunSound:b=yes. I seems useLoopsForGunSound:b=yes doesn't work for you, I don't know why. But, I tested production version today - it works correctly for me, with useLoopsForGunSound:b=yes. Send me your clog file, please.


[2020_12_25_22_39_24__24236.zip](https://github.com/GaijinEntertainment/fmod_studio_warthunder_for_modders/files/5742332/2020_12_25_22_39_24__24236.zip)
Hope this helps, although i asked my colleagues to make same steps, none of them got it working.

**Comment by Uchuujin01** [comment] 2020-12-25 19:56
@787992 here what I see in your log:

sound{
  speakerMode:t="stereo"
  fmod_sound_enable:b=yes
  enable_mod:b=yes
  useLoopsForGunSounds:b=no
}

So, it's explain the situation,  useLoopsForGunSounds:b=no. Check it please. I don't know why it can be so, if in your log will be another value (yes) for this variable, it needs investigation.

**Comment by 787992** [comment] 2020-12-25 20:04
> So, it's explain the situation, useLoopsForGunSounds:b=no. Check it please. I don't know why it can be so, if in your log will be another value (yes) for this variable, it needs investigation.

Oh, i did it manually, still no or yes does nothing (literally tried everything), i can send other clog with "yes" line if it will helps

**Comment by 787992** [comment] 2020-12-25 20:18
Could you double check it with any MG in game?

**Comment by Uchuujin01** [comment] 2020-12-25 20:24
@787992 I can't check anything right now, but, I cheched this feature with Shilka ZSU-23-4 today, and, it worked with looping feature just fine. On production client. Can you please check it?

**Comment by 787992** [comment] 2020-12-25 20:26
@Uchuujin01 Sure, one sec

**Comment by RadonSound** [comment] 2020-12-25 20:44
So i started from scratch with the newest project without any copy&paste actions. 
I've made the loop event like in the example but have the same issue.
I testet with the MG34 and Shilka
The mg34 made the same sound as the video from @787992 
And the Shilka only played the tail sound (no shot sound)
I tested to set the config to read-only>didnt changed it 

https://youtu.be/mPvyK0G7vBg Ingame test at the end

**Comment by 787992** [comment] 2020-12-25 20:52
> I can't check anything right now, but, I cheched this feature with Shilka ZSU-23-4 today, and, it worked with looping feature just fine. On production client. Can you please check it?

Exact same behaviour as m2hb mg, so yeah, i'm out of ideas.
Maybe it working for you because config is not restricted for developers? So existence of allowedconfigoverrides making sense?

**Comment by Uchuujin01** [comment] 2020-12-25 20:54
@787992 @RadonSound guys, I don't know what to suggest for now ( I swear, I tested this feature on production client today, and it worked. I belive you that it doesn't work for now. But I don't know why. I'll ask our audio programmer to check this out on monday, ok? But, it is strange, I asked him already today, and we both checked this feature, it worked (

**Comment by 787992** [comment] 2020-12-25 21:02
> guys, I don't know what to suggest for now ( I swear, I tested this feature on production client today, and it worked. I belive you that it doesn't work for now. But I don't know why. I'll ask our audio programmer to check this out on monday, ok? But, it is strange, I asked him already today, and we both checked this feature, it worked (

it's alright, just weird that this thing refuses to work and works for devs at this point
No rush though, have a nice holidays!

**Comment by RadonSound** [comment] 2020-12-25 21:04
@Uchuujin01 I understand i dont want to make any pressure at all in holidays
It is really strange im also trying to figure out where the devil sits
In my video i noticed something,
on second 00:18 the assign shilka event only plays the tailsound such as the ingame test at the end.
on 00:22, the event plays the loop how it should be but the event is unassign.
Could the be the problem somehow?

**Comment by 787992** [comment] 2020-12-25 21:14
> the event plays the loop how it should be but the event is unassign.

This is just the copy of original event, it has nothing to do with loop system

**Comment by Uchuujin01** [comment] 2020-12-25 21:20
I'm sure we'll figure out this problem, we'll take a look at this issue on monday

**Comment by RadonSound** [comment] 2021-01-01 18:25
Happy new year guys and stay healthy! o7

**Comment by Uchuujin01** [comment] 2021-01-05 14:02
@RadonSound thank you! Happy new year )

**Comment by RadonSound** [comment] 2021-01-08 11:56
hello,
i would like to ask if there are any news because of the loop issue? 
(sorry if its a bit early to ask because of holidays)

**Comment by Uchuujin01** [comment] 2021-01-11 11:48
@RadonSound hello! I just started my first work day in this year, so, there are no news still ) I'll try to reproduce your problem and then write to you. Meanwhile, could you please write to me your way to reproduce the bug (all config.blk changes, sound event changes)? Maybe I missed something.

**Comment by Uchuujin01** [comment] 2021-01-12 10:21
@RadonSound @787992 Hello! I reproduced the problem with loops, it really doesn't work in some cases. We working on it, sorry for this.

**Comment by Uchuujin01** [comment] 2021-01-12 12:18
Fixed, will be on production cirquit with the next hotfix patch.

**Comment by 787992** [comment] 2021-01-13 11:14
> Fixed, will be on production cirquit with the next hotfix patch.

Sweeeet. Kinda curious what was the issue, i tested it with bunch of people, nobody couldn't get it it to work.

**Comment by Uchuujin01** [comment] 2021-01-13 11:25
In short, there is one of the config files, that can overload some game parameters on production cirquit, and it overloaded useLoopsForGunSounds with "no" value, in some cases.

**Comment by Uchuujin01** [comment] 2021-01-13 13:50
@787992 @RadonSound check please if useLoopsForGunSounds works now. It should. Hotfix was uploaded recently.

**Comment by RadonSound** [comment] 2021-01-13 14:18
@Uchuujin01 it works! 😁 tested with mg34

**Comment by Uchuujin01** [comment] 2021-01-13 14:29
Yeah! ) Glad to read this )

**Closed** 2021-01-22 14:14 UTC
